[package]
name = "fcmp_rust"
version = "0.0.0"
edition = "2021"

[lib]
name = "fcmp_rust"
crate-type = ["staticlib"]

[dependencies]
rand_core = { version = "0.6", features = ["getrandom"] }

transcript = { package = "flexible-transcript", git = "https://github.com/kayabaNerve/fcmp-plus-plus", features = ["recommended"] }
helioselene = { git = "https://github.com/kayabaNerve/fcmp-plus-plus" }
ciphersuite = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", features = ["ed25519", "helioselene"] }

generalized-bulletproofs = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", features = ["tests"] }

ec-divisors = { git = "https://github.com/kayabaNerve/fcmp-plus-plus", features = ["ed25519"] }
full-chain-membership-proofs = { git = "https://github.com/kayabaNerve/fcmp-plus-plus" }

[patch.crates-io]
crypto-bigint = { git = "https://github.com/kayabaNerve/crypto-bigint", branch = "c-repr" }

[profile.dev]
lto = "off"

[profile.release]
lto = "off"
