sudo: required
dist: trusty
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - build-essential
    - cmake
    - doxygen
    - g++
    - gcc
    - clang
    - graphviz
    - libboost1.55-all-dev
    - libdb++-dev
    - libdb-dev
    - libgtest-dev
    - libminiupnpc-dev
    - libssl-dev
    - libssl1.0.0
    - libunbound-dev
    - libunwind8-dev
    #sources:
    #- ubuntu-toolchain-r-test
script: make -j2 && travis_wait make -j2 release-test && HAVE_DOT=YES doxygen Doxyfile
notifications:
  email: false
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#monero-dev"
    nick: monero
    template:
      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
