sudo: required
dist: trusty
language: cpp

matrix:
  include:

  #
  # Coveralls.io
  #
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - doxygen
          - g++
          - gcc
          - clang
          - graphviz
          - libdb++-dev
          - libdb-dev
          - libgtest-dev
          - libminiupnpc-dev
          - libssl-dev
          - libssl1.0.0
          - libunbound-dev
          - libunwind8-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:kojoley/boost
      - sudo apt-get -q update
      - pip install --user cpp-coveralls
    install:
      - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}
    script:
      - make -j2 coverage
    after_success:
      - travis_wait coveralls -e external -e tests -e cmake -e contrib -e translations -e utils --gcov-options '\-lp' &> /dev/null

  #
  # Monero release-all (gcc)
  #
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - doxygen
          - g++
          - gcc
          - clang
          - graphviz
          - libdb++-dev
          - libdb-dev
          - libgtest-dev
          - libminiupnpc-dev
          - libssl-dev
          - libssl1.0.0
          - libunbound-dev
          - libunwind8-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:kojoley/boost
      - sudo apt-get -q update
    install:
      - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}
    script:
      - make -j2 && HAVE_DOT=YES doxygen Doxyfile

  #
  # Monero release-all (clang)
  #
  - os: linux
    compiler: clang
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - doxygen
          - clang
          - graphviz
          - libdb++-dev
          - libdb-dev
          - libgtest-dev
          - libminiupnpc-dev
          - libssl-dev
          - libssl1.0.0
          - libunbound-dev
          - libunwind8-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:kojoley/boost
      - sudo apt-get -q update
    install:
      - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}
    script:
      - make -j2 && HAVE_DOT=YES doxygen Doxyfile

notifications:
  email: false
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#monero-bots"
    nick: monero
    template:
      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
