[package]
name = "fcmp_pp_rust"
version = "0.0.0"
edition = "2021"

[lib]
name = "fcmp_pp_rust"
crate-type = ["staticlib"]

[dependencies]
rand_core = { version = "0.6", default-features = false }

multiexp = "0.4"
ciphersuite = { version = "0.4.2", features = ["ed25519"] }
dalek-ff-group = "0.4.4"
helioselene = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf" }

generalized-bulletproofs = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf" }
ec-divisors = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf", features = ["ed25519"] }
full-chain-membership-proofs = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf" }

monero-generators = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf" }
monero-fcmp-plus-plus = { git = "https://github.com/monero-oxide/monero-oxide", rev = "1b409de0a377f891575693fd86a25e8f3c24d5bf" }

[patch.crates-io]
crypto-bigint = { git = "https://github.com/kayabaNerve/crypto-bigint", branch = "c-repr" }

[profile.dev]
lto = "off"
panic = "abort"
overflow-checks = true

[profile.release]
lto = "off"
panic = "abort"
overflow-checks = true

[profile.dev.package]
subtle = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }

ff = { opt-level = 3 }
group = { opt-level = 3 }

crypto-bigint = { opt-level = 3 }
dalek-ff-group = { opt-level = 3 }
helioselene = { opt-level = 3 }

multiexp = { opt-level = 3 }

ec-divisors = { opt-level = 3 }
generalized-bulletproofs = { opt-level = 3 }
generalized-bulletproofs-circuit-abstraction = { opt-level = 3 }
generalized-bulletproofs-ec-gadgets = { opt-level = 3 }
full-chain-membership-proofs = { opt-level = 3 }

monero-fcmp-plus-plus = { opt-level = 3 }
